[package]
name = "tokenthing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
regex = "1.0"

[[bin]]
name = "tokenthing"
path = "src/main.rs"

